(function(){
  'use strict';
  const data=window.ParentLessons,model=window.ParentProgress,main=document.getElementById('main');
  let state=model.empty(),memoryOnly=false,loadWarning='',pendingImport=null,retainedRaw=null;
  try{const raw=localStorage.getItem(model.KEY);if(raw){retainedRaw=raw;const parsed=model.validate(JSON.parse(raw),data);state=parsed.state;if(parsed.unknown.length){localStorage.setItem(model.KEY+'.previous',raw);loadWarning='В учебнике появились изменения. Известные занятия сохранены. Предыдущая запись с отсутствующими занятиями сохранена отдельно в этом браузере.';}}}
  catch{if(retainedRaw){try{localStorage.setItem(model.KEY+'.previous',retainedRaw);}catch{memoryOnly=true;}}else memoryOnly=true;loadWarning='Сохранённый прогресс сейчас недоступен. Можно заниматься дальше и сохранить новый файл прогресса.';}
  function node(tag,text,attrs={}){const e=document.createElement(tag);if(text!==null)e.textContent=text;for(const [k,v]of Object.entries(attrs))e.setAttribute(k,String(v));return e;}
  function button(text,action,attrs={}){const b=node('button',text,{type:'button',...attrs});b.addEventListener('click',action);return b;}
  function link(text,url){return node('a',text,{href:url});}
  function save(){try{localStorage.setItem(model.KEY,JSON.stringify(state));memoryOnly=false;}catch{memoryOnly=true;}storageNote();}
  function storageNote(){document.getElementById('storage-note').textContent=memoryOnly?'Браузер разрешил хранить прогресс только пока эта страница открыта. Сохраните файл прогресса в помощи.':'Прогресс сохраняется в этом браузере на этом устройстве. Очистка данных браузера может его удалить.';}
  function preferences(){document.documentElement.dataset.theme=state.theme;document.documentElement.classList.toggle('large-text',state.large);document.getElementById('text-size').setAttribute('aria-pressed',String(state.large));document.querySelector('#text-size span').textContent=state.large?'Обычный размер':'Крупнее';document.getElementById('theme').setAttribute('aria-pressed',String(state.theme==='dark'));document.querySelector('#theme span').textContent=state.theme==='dark'?'Светлый фон':'Тёмный фон';}
  document.getElementById('text-size').addEventListener('click',()=>{state.large=!state.large;preferences();save();});
  document.getElementById('theme').addEventListener('click',()=>{state.theme=state.theme==='light'?'dark':'light';preferences();save();});
  function navigate(route){history.pushState(null,'','#'+route);render();}
  document.addEventListener('click',event=>{const a=event.target.closest('a[href^="#"]');if(a&&a.getAttribute('href')!=='#main'&&!event.ctrlKey&&!event.metaKey){event.preventDefault();navigate(a.getAttribute('href').slice(1));}});
  window.addEventListener('popstate',render);window.addEventListener('hashchange',render);
  function title(text,kicker){if(kicker)main.append(node('p',kicker,{class:'eyebrow'}));main.append(node('h1',text,{tabindex:'-1'}));}
  function back(){main.append(button('← К занятиям',()=>navigate('home'),{class:'text-button back'}));}
  function feedback(target,text,ok=false){target.textContent=text;target.dataset.result=ok?'success':'retry';target.hidden=false;}
  function illustration(){
    const figure=node('figure',null,{class:'welcome-art'});
    figure.append(node('img',null,{src:'assets/together-room.png',width:'1536',height:'1024',alt:'Иллюстрация: двое старших вместе пробуют ноутбук за столом с чаем. Рядом отдыхает кот.',fetchpriority:'high',decoding:'async'}));
    figure.append(node('span',null,{class:'room-light','aria-hidden':'true'}));
    const caption=node('figcaption',null,{class:'scene-note'});caption.append(node('span','☀',{class:'scene-note-icon','aria-hidden':'true'}),node('span','Можно спокойно попробовать.'));figure.append(caption);return figure;
  }
  function home(){
    const hero=node('section',null,{class:'welcome'}),copy=node('div',null,{class:'welcome-copy'});
    const resume=model.next(state,data),count=model.summary(state,data),actions=node('div',null,{class:'actions'});
    copy.append(node('p','По-русски. В вашем темпе.',{class:'welcome-note'}),node('h1','Разберёмся\nвместе.',{tabindex:'-1'}),node('p',state.cursor||count.completed?'Начнём с того места, где вы остановились.':'Сначала — один клик.',{class:'lead'}));
    actions.append(button(state.cursor||count.completed?'Продолжить →':'Попробовать первый клик →',()=>navigate('lesson/'+(resume?.id||data.lessons[0].id)),{class:'primary',id:'start'}));
    copy.append(actions,button('Хочу выбрать тему',()=>navigate('lessons'),{class:'text-button choose-topic'}));
    if(count.completed)copy.append(node('p',count.completed===count.total?'Все текущие занятия пройдены. Можно повторить любое.':'Уже получается: '+count.completed+' из '+count.total+' занятий.',{class:'progress-summary'}));
    copy.append(node('p','Интернет большой. Начнём с чашки.',{class:'welcome-joke'}));
    hero.append(illustration(),copy);main.append(hero);
    if(loadWarning)main.append(node('p',loadWarning,{class:'notice',role:'status'}));
  }
  function chapterCards(expanded){const grid=node('div',null,{class:'chapter-grid'});for(const chapter of data.chapters){const card=node('section',null,{class:'chapter'}),head=node('div',null,{class:'chapter-heading'});head.append(node('span',chapter.icon,{class:'chapter-symbol','aria-hidden':'true'}),node('h2',chapter.title));card.append(head,node('p',chapter.description));const lessons=data.lessons.filter(l=>l.chapter===chapter.id);if(expanded){const list=node('ul',null,{class:'lesson-list'});for(const lesson of lessons){const li=node('li'),b=button((state.done.includes(lesson.id)?'✓ ':'')+lesson.title,()=>navigate('lesson/'+lesson.id),{'data-lesson':lesson.id});li.append(b);list.append(li);}card.append(list);}else card.append(button('Посмотреть занятия →',()=>navigate('chapter/'+chapter.id),{class:'text-button'}));grid.append(card);}main.append(grid);}
  function catalogue(chapterId){back();title('Выберите, что хочется освоить','ЗАНЯТИЯ');main.append(node('p','Можно начать с любого занятия. Здесь нет экзамена и гонки.',{class:'lead'}));chapterCards(true);if(chapterId){const index=data.chapters.findIndex(c=>c.id===chapterId);const card=main.querySelectorAll('.chapter')[index];if(card){card.querySelector('h2').setAttribute('tabindex','-1');card.querySelector('h2').focus();card.scrollIntoView({block:'start'});}}}
  function help(){
    back();title('Всё можно найти и продолжить','ПОМОЩЬ');
    const guide=node('section',null,{class:'paper'});guide.append(node('h2','Как пользоваться'),node('p','Нажмите «Попробовать» или «Продолжить». Прочитайте короткое задание, попробуйте действие и посмотрите ответ. Кнопка «Подсказка» поможет, если что-то непонятно. Занятие можно повторять.'),node('p','Мышь: один клик левой кнопкой. Телефон: касание. Клавиатура: Tab выбирает кнопку, Enter нажимает. Для чтения крупнее используйте «Аа» вверху страницы.'));
    main.append(guide);
    const transfer=node('section',null,{class:'paper'});transfer.append(node('h2','Прогресс на другом устройстве'),node('p','Без аккаунта каждое устройство хранит свой прогресс. Чтобы перенести его, сохраните файл здесь. На другом устройстве откройте этот учебник и выберите сохранённый файл. Он содержит пройденные занятия и настройки чтения, а не тексты учебных сообщений.'));
    const actions=node('div',null,{class:'actions'}),notice=node('p','',{class:'feedback',role:'status',hidden:''});
    actions.append(button('Сохранить файл прогресса',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=link('Файл прогресса',url);a.download='мой-учебный-прогресс.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);feedback(notice,'Браузер получил файл для сохранения. Посмотрите список загрузок или выбранную папку.',true);},{class:'primary',id:'export-progress'}));
    const input=node('input',null,{type:'file',id:'progress-file',accept:'.json,application/json'}),label=node('label','Открыть файл прогресса',{for:'progress-file',class:'file-label'});transfer.append(actions,label,input,notice);
    input.addEventListener('change',()=>{pendingImport=null;const file=input.files[0];if(!file)return;if(file.size>200000){feedback(notice,'Этот файл слишком большой для учебного прогресса. Выберите сохранённый JSON-файл.');return;}const reader=new FileReader();reader.onerror=()=>feedback(notice,'Браузер не смог прочитать файл. Попробуйте выбрать его снова.');reader.onload=()=>{try{const result=model.validate(JSON.parse(reader.result),data);pendingImport=result;feedback(notice,'Файл прочитан. Найдено пройденных занятий: '+result.state.done.length+'.'+(result.unknown.length?' Некоторые названия отсутствуют в текущем учебнике: '+result.unknown.join(', ')+'. Они остаются в вашем исходном файле.':''));const apply=button('Добавить этот прогресс',()=>{if(!pendingImport)return;state=model.merge(state,pendingImport.state);pendingImport=null;preferences();save();feedback(notice,'Прогресс добавлен. Ваши ранее пройденные занятия сохранены.',true);apply.remove();},{class:'primary',id:'confirm-import'});transfer.querySelector('#confirm-import')?.remove();transfer.append(apply);}catch(e){transfer.querySelector('#confirm-import')?.remove();feedback(notice,e.message==='Unexpected end of JSON input'?'Файл повреждён. Текущий прогресс сохранён.':'Файл не подошёл. '+(e instanceof SyntaxError?'Нужен JSON-файл прогресса этого учебника.':e.message));}};reader.readAsText(file);});main.append(transfer);
    const glossary=node('section',null,{class:'paper'});glossary.append(node('h2','Частые слова на немецком экране'));const dl=node('dl',null,{class:'glossary'});for(const [de,ru]of [['Einstellungen','Настройки'],['Speichern','Сохранить'],['Abbrechen','Отменить'],['Schließen','Закрыть'],['Suchen','Искать'],['Downloads / Herunterladen','Загрузки / Скачать'],['Zurück','Назад'],['Weiter','Дальше']])dl.append(node('dt',de,{lang:'de'}),node('dd',ru));glossary.append(dl);main.append(glossary);
    const sources=node('section',null,{class:'paper'});sources.append(node('h2','Если хочется узнать больше'),node('p','Следующие ссылки открывают настоящие сайты. Их вид и правила могут меняться. Справка помогает свериться с текущими настройками.'));const list=node('ul',null,{class:'source-list'});for(const source of data.sources){const li=node('li');li.append(link(source.title+' ↗',source.url));list.append(li);}sources.append(list);main.append(sources);
  }
  function lessonView(id){
    const lesson=data.lessons.find(l=>l.id===id);if(!lesson){back();title('Это занятие сейчас не найдено');main.append(node('p','Можно вернуться к списку и выбрать другую тему. Ваш прогресс сохранён.'));return;}
    let index=state.cursor?.id===id?state.cursor.step:0;
    back();title(lesson.title);
    const explanation=node('details',null,{class:'lesson-explanation'});explanation.append(node('summary','Как это работает'),node('p',lesson.intro,{class:'lesson-intro'}),node('p',lesson.joke,{class:'joke'}));main.append(explanation);
    const host=node('section',null,{class:'exercise', 'aria-label':'Учебное упражнение'});main.append(host);
    function complete(){state.done=[...new Set([...state.done,id])];state.cursor=null;save();host.replaceChildren(node('p','✓ Занятие пройдено',{class:'eyebrow'}),node('h2','Получилось!',{tabindex:'-1'}),node('p',lesson.takeaway,{class:'takeaway'}));const nextLesson=data.lessons.find((l,i)=>i>data.lessons.indexOf(lesson)&&!state.done.includes(l.id))||data.lessons.find(l=>!state.done.includes(l.id));const actions=node('div',null,{class:'actions'});if(nextLesson)actions.append(button('Следующее занятие →',()=>navigate('lesson/'+nextLesson.id),{class:'primary'}));actions.append(button('К занятиям',()=>navigate('home'),{class:'secondary'}),button('Повторить',()=>{index=0;stepView();},{class:'text-button'}));host.append(actions);host.querySelector('h2').focus();}
    function stepView(){
      if(index===lesson.steps.length){complete();return;}
      state.cursor={id,step:index};save();host.classList.remove('has-success');const step=lesson.steps[index];host.replaceChildren(node('p','Шаг '+(index+1)+' из '+lesson.steps.length,{class:'step-count'}),node('h2',step.prompt,{tabindex:'-1'}));
      const work=node('div',null,{class:'practice'}),response=node('p','',{class:'feedback',role:'status',hidden:''}),controls=node('div',null,{class:'exercise-controls'});
      let solved=false;
      function respond(ok,message){feedback(response,message,ok);host.classList.toggle('has-success',ok);if(ok&&!solved){solved=true;const next=button(index===lesson.steps.length-1?'Завершить занятие →':'Дальше →',()=>{index++;stepView();},{class:'primary',id:'next-step'});controls.append(next);next.focus();}}
      practice(step,work,respond);const hint=button('Подсказка',()=>feedback(response,step.hint),{class:'secondary',id:'hint'});controls.append(hint);
      if(index>0)controls.append(button('← Предыдущий шаг',()=>{index--;stepView();},{class:'text-button'}));host.append(work,response,controls);host.querySelector('h2').focus();
    }
    stepView();
  }
  function practice(step,work,respond){
    const ok=(text='Верно! Можно идти дальше.')=>respond(true,text),retry=(text='Попробуйте ещё раз. Подсказка поможет.')=>respond(false,text);
    if(step.kind==='choice'){const choices=node('div',null,{class:'choices'});step.options.forEach((label,i)=>choices.append(button(label,()=>i===step.answer?ok():retry(step.hint),{'data-option':i})));work.append(choices);return;}
    if(['text','search','message'].includes(step.kind)){
      const form=node('form'),input=node(step.kind==='message'?'textarea':'input',null,{id:'practice-text',maxlength:1000,autocomplete:'off',spellcheck:'true'});if(input.tagName==='INPUT')input.type='text';
      form.append(node('label',step.label,{for:'practice-text'}),input);
      if(step.example)form.append(button('Вставить образец',()=>{input.value=step.example;input.focus();},{class:'secondary',id:'example'}));
      form.append(node('button',step.kind==='search'?'Искать в учебном примере':step.kind==='message'?'Посмотреть черновик':'Проверить',{type:'submit',class:'primary'}));
      const results=node('div',null,{class:'practice-results'});form.addEventListener('submit',event=>{event.preventDefault();const text=input.value.trim(),lower=text.toLocaleLowerCase('ru');const valid=step.accepted?step.accepted.includes(lower):step.words.every(word=>lower.includes(word))&&(step.kind!=='message'||text.includes('?'));if(!valid){retry(step.hint);return;}results.replaceChildren();if(step.kind==='search'){results.append(node('h3','Учебные результаты'),node('p','Пересадка орхидеи: признаки, грунт, пошаговый уход.'),node('p','Сравните автора, дату и объяснение совета в разных источниках. Это учебная выдача, а не поиск в интернете.'));}if(step.kind==='message'){results.append(node('h3','Ваш учебный черновик'),node('p',text,{class:'message-preview'}),node('p','Черновик остаётся в этом упражнении. На настоящем сайте вы отдельно проверяете адресата и отправляете сообщение.'));}ok(step.kind==='message'?'Черновик готов к перечитыванию.':step.kind==='search'?'Запрос понятный: есть тема и действие.':'Получилось: слово написано и проверено.');});work.append(form,results);return;
    }
    if(step.kind==='point'){
      const row=node('div',null,{class:'object-row object-stage'}),tip=node('p','Подведите стрелку к предмету. Подпись поможет.',{class:'small-note',id:'point-tip',role:'status'});
      const art={
        'Письмо':'<svg viewBox="0 0 230 200" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="116" cy="173" rx="84" ry="12" fill="#d9c7aa" opacity=".5"/><rect x="38" y="56" width="151" height="108" rx="12" fill="#d8e7eb" stroke="#518098" stroke-width="3"/><path d="M42 65l73 57 70-57M42 157l52-45M185 157l-51-45" fill="none" stroke="#518098" stroke-width="3" stroke-linejoin="round"/><path d="M102 46h35v31h-35z" fill="#f7b184" stroke="#ab6552" stroke-width="2"/><path d="M110 56h19M110 63h14" stroke="#ab6552" stroke-width="2"/></svg>',
        'Чашка':'<svg viewBox="0 0 230 200" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><ellipse cx="112" cy="173" rx="83" ry="13" fill="#d9c7aa" opacity=".5"/><ellipse cx="110" cy="165" rx="80" ry="12" fill="#fff5e2" stroke="#b1956d" stroke-width="2"/><path d="M157 67h18c36 0 37 60 1 60h-20" fill="none" stroke="#f9ebcf" stroke-width="16"/><path d="M158 67h18c36 0 37 60 0 60" fill="none" stroke="#b1956d" stroke-width="2"/><path d="M53 65h108v63c0 39-108 39-108 0z" fill="#fff4da" stroke="#b1956d" stroke-width="3"/><ellipse cx="107" cy="65" rx="54" ry="15" fill="#f4dcc0" stroke="#b1956d" stroke-width="3"/><ellipse cx="107" cy="66" rx="43" ry="9" fill="#b87b48"/><path d="M91 111q16-25 30 0q-13 23-30 0" fill="#ee9c78"/><path class="cup-steam" d="M88 42c-14-13 13-16 0-31M111 40c-13-14 13-17 0-31" fill="none" stroke="#a88b69" stroke-width="3" stroke-linecap="round"/></svg>'
      };
      for(const [glyph,label]of [['✉','Письмо'],['☕','Чашка']]){
        let b;b=button('',()=>{if(label==='Чашка'){b.classList.add('is-chosen');ok('Чашку нашли. Получилось!');}else retry('Это письмо. Ищем чашку с ручкой.');},{class:'object-button','aria-describedby':'point-tip'});
        const drawing=node('span',null,{class:'object-drawing','aria-hidden':'true'});drawing.innerHTML=art[label];b.append(drawing,node('span',glyph+' '+label,{class:'object-label'}));
        const describe=()=>{tip.textContent=label==='Чашка'?'Чашка с ручкой — сюда можно нажать.':'Это письмо. Ищем чашку с ручкой.';};b.addEventListener('pointerenter',describe);b.addEventListener('focus',describe);row.append(b);
      }
      work.append(row,tip);return;
    }
    if(step.kind==='window'){let minimized=false,closed=false;const box=node('div',null,{class:'demo-window'}),bar=node('div',null,{class:'demo-title'}),body=node('p','Учебное окно открыто. Его можно свернуть и вернуть.'),dock=node('div',null,{class:'demo-dock'});bar.append(node('strong','Моя памятка'),button('— Свернуть',()=>{minimized=true;body.hidden=true;dock.replaceChildren(button('▣ Вернуть окно',()=>{body.hidden=false;ok('Окно вернулось. Свернуть — значит временно убрать его.');},{class:'primary'}));}),button('× Закрыть',()=>{closed=true;body.hidden=true;dock.replaceChildren(button('Открыть снова',()=>{closed=false;body.hidden=false;dock.replaceChildren();retry('Окно снова открыто. Теперь попробуйте «— Свернуть».');},{class:'secondary'}));retry('Вы закрыли учебное окно. Его можно снова открыть, а затем свернуть.');}));box.append(bar,body);work.append(box,dock);return;}
    if(step.kind==='scroll'){const letter=node('div',null,{class:'scroll-letter',tabindex:'0','aria-label':'Учебное письмо, прокрутите до конца'});letter.append(node('h3','Письмо от Юри'));for(const p of ['Привет! Здесь мы пробуем прокрутку.','Когда текст длинный, продолжение находится ниже.','Колёсико мыши помогает двигаться по странице. На телефоне проведите пальцем вверх.','С клавиатуры можно выбрать это письмо и нажать Page Down или стрелку вниз.','Пока крутим — компьютер цел. Да, проверили ещё раз.','Вот и конец письма. Теперь нажмите кнопку под этим текстом.'])letter.append(node('p',p));letter.append(button('Нашёл конец',()=>ok('Вы нашли продолжение письма. Иногда ответ находится чуть ниже.'),{class:'primary',id:'scroll-end'}));work.append(letter);return;}
    if(step.kind==='tabs'){let visited=false;const browser=node('div',null,{class:'demo-window'}),tabs=node('div',null,{class:'demo-tabs','aria-label':'Учебные вкладки'}),content=node('div',null,{class:'tab-content'});const mail=button('✉ Письмо',()=>{content.textContent='Письмо снова открыто.';mail.setAttribute('aria-pressed','true');recipe.setAttribute('aria-pressed','false');visited?ok('Посмотрели другую вкладку и вернулись к письму.'):retry('Сначала загляните на вкладку «Рецепт».');},{'aria-pressed':'true'}),recipe=button('♧ Рецепт',()=>{visited=true;recipe.setAttribute('aria-pressed','true');mail.setAttribute('aria-pressed','false');content.textContent='Учебный рецепт: чай, вода и хорошая компания. Теперь вернитесь на «Письмо».';},{'aria-pressed':'false'});tabs.append(mail,recipe);content.textContent='Учебное письмо. Рядом есть ещё одна вкладка.';browser.append(tabs,content);work.append(browser);return;}
    if(step.kind==='translate'){work.append(node('p','Немецкая кнопка: Speichern',{class:'german-label'}));for(const label of ['Сохранить','Закрыть','Искать'])work.append(button(label,()=>label==='Сохранить'?ok('Speichern — сохранить. Теперь эта кнопка знакома.'):retry(step.hint),{class:'choice-button'}));return;}
    if(step.kind==='video'){let played=false,running=false;const stage=node('div',null,{class:'video-demo','aria-label':'Учебная анимация'});stage.append(node('span','✳',{class:'video-flower','aria-hidden':'true'}),node('p','Учебная анимация · без звука'));const play=button('▷ Воспроизвести',()=>{running=!running;stage.classList.toggle('playing',running);play.textContent=running?'Ⅱ Пауза':'▷ Воспроизвести';if(running)played=true;else if(played)ok('Вы управляете воспроизведением. Теперь анимация на паузе.');},{class:'primary','aria-pressed':'false'});play.addEventListener('click',()=>play.setAttribute('aria-pressed',String(running)));work.append(stage,play);return;}
    if(step.kind==='listing'||step.kind==='photos'){const row=node('div',null,{class:'object-row'});const entries=step.kind==='photos'?[['♧','Цветок'],['▰','Стул'],['☕','Чашка']]:[['▰','Целый стул · самовывоз'],['▰','Сломанная ножка · требуется ремонт'],['◫','Стол · самовывоз']];for(const [i,[icon,label]]of entries.entries()){const b=button(icon+' '+label,()=>i===(step.kind==='photos'?1:0)?ok(step.kind==='photos'?'Фото стула добавлено к учебному черновику.':'Подходит: нужный предмет, целое состояние, самовывоз.'):retry(step.hint),{class:'listing-card'});row.append(b);}work.append(row);return;}
    if(step.kind==='files'){const folder=button('▤ Downloads / Загрузки',()=>{work.replaceChildren(node('p','Учебная папка «Загрузки»'));for(const file of ['Памятка.pdf','Семейное-фото.jpg'])work.append(button('▧ '+file,()=>file==='Памятка.pdf'?ok('Вы нашли документ в учебной папке «Загрузки».'):retry('Это фотография. Ищем документ «Памятка.pdf».'),{class:'file-card'}));},{class:'file-card'});work.append(folder);return;}
    retry('Для этого задания нужен новый учебный шаг. Можно выбрать другое занятие.');
  }
  function render(){main.replaceChildren();const route=location.hash.slice(1)||'home';document.body.dataset.view=route.startsWith('lesson/')?'lesson':route==='help'?'help':route==='lessons'||route.startsWith('chapter/')?'catalogue':'home';if(route.startsWith('lesson/'))lessonView(route.slice(7));else if(route==='help')help();else if(route==='lessons')catalogue();else if(route.startsWith('chapter/'))catalogue(route.slice(8));else home();if(!route.startsWith('chapter/')){window.scrollTo(0,0);main.querySelector('h1')?.focus({preventScroll:true});}}
  preferences();storageNote();render();
})();
